# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  # boot.extraModulePackages = [ config.boot.kernelPackages.nvidia_x11 ];
  # boot.extraModprobeConfig = ''
  # options bbswitch load_state=-1 unload_state=1 nvidia-drm
  # '';
  # boot.blacklistedKernelModules = [
  #   "nouveau"
  #   "rivafb"
  #   "nvidiafb"
  #   "rivatv"
  #   "nv"
  #   "uvcvideo"
  # ];
  # boot.blacklistedKernelModules = [ "nvidiafb" "rivafb" "nouveau" "rivatv" "nv" "uvcvideo" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fb54d21d-a3a3-4af3-bd6a-241eeed4c88c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7A98-77BD";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/15c2532b-c2f9-4108-90b2-c0494e05deb4"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
